SCHEMA = {
 'ai_agents':'id store_id welcome_message faq updated_at',
 'ai_conversations':'id agent_id customer_name last_message_at status',
 'ai_messages':'id conversation_id sender content created_at',
 'automation_campaigns':'id store_id name target_audience message_content status scheduled_at created_at',
 'contact_submissions':'id name email subject message created_at',
 'deliveries':'id order_id delivery_person_id status pickup_address delivery_address created_at pickup_coords delivery_coords',
 'delivery_locations':'delivery_person_id lat lng updated_at',
 'delivery_payouts':'id delivery_id amount status paid_at created_at',
 'digital_product_files':'id product_id file_name file_url created_at',
 'discounts':'id store_id code discount_type value usage_limit usage_count expires_at created_at',
 'hotel_rooms':'id store_id number type price_per_night status created_at',
 'maintenance_logs':'id equipment_id type description cost performed_by date created_at',
 'messages':'id sender_id receiver_id order_id content created_at read_at',
 'order_items':'id order_id product_id quantity price',
 'orders':'id customer_id store_id status total created_at delivery_address commission_fee subtotal service_fee delivery_fee delivery_lat delivery_lng payment_method notes discount_code discount_amount tax_amount shipping_rate_id',
 'products':'id store_id name description price category image_url stock created_at discount product_type requires_shipping weight_kg tax_id metadata',
 'profiles':'id full_name phone role created_at address email',
 'restaurant_tables':'id store_id number capacity status created_at',
 'reviews':'id spot_id user_id rating comment created_at',
 'service_categories':'id name description created_at',
 'service_types':'id name commission_rate',
 'shipping_rates':'id zone_id name price min_order_subtotal max_order_subtotal created_at',
 'shipping_zones':'id store_id name countries provinces created_at',
 'store_activity_logs':'id store_id user_id activity created_at',
 'store_equipment':'id store_id name description serial_number purchase_date status next_maintenance_date created_at updated_at',
 'store_members':'id store_id user_id role created_at',
 'stores':'id owner_id name description category address logo_url created_at stripe_connect_id service_category_id cuisine_type star_rating activity_type interest_type contact_email contact_phone whatsapp facebook_url instagram_url status disabled_modules',
 'subscriptions':'id store_id plan_id status stripe_customer_id stripe_subscription_id current_period_start current_period_end created_at updated_at',
 'support_tickets':'id created_by store_id subject message status admin_response created_at updated_at',
 'taxes':'id store_id name rate is_default created_at',
 'tourism_categories':'id name description created_at',
 'tourism_spots':'id name description address latitude longitude category_id image_urls contact_phone website created_at',
 'transactions':'id order_id store_id product_id service_type_id amount commission_rate created_at commission_fee',
 'user_addresses':'id user_id name address_line city is_default created_at',
 'user_notifications':'id user_id title message type read created_at',
 'user_payment_methods':'id user_id last_four brand exp_month exp_year is_default created_at',
 'wishlist':'id user_id product_id created_at',
}
SCHEMA = {t:set(c.split()) for t,c in SCHEMA.items()}
